"""update uptade_at users table

Revision ID: d4d59637fd4d
Revises: 6e44dd0d3a6f
Create Date: 2024-06-24 19:43:58.580923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d59637fd4d'
down_revision: Union[str, None] = '6e44dd0d3a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
